namespace GB_Platformer
{
    public enum Track
    {
        Idle,
        Run,
        Jump,
        Fall,
        TakeHit,
        Death,
        Attack1,
        Attack2,
        Attack3,
        Attack4,
        Coin,
        Projectile,
        Skeleton_Idle,
        Skeleton_Walk,
        Skeleton_Death,
        Skeleton_TakeHit,
        Skeleton_Attack1,
        Skeleton_Attack2,
        Skeleton_Shield,
        FlyingEye_Flight,
        FlyingEye_Death,
        FlyingEye_TakeHit,
        FlyingEye_Attack1,
        FlyingEye_Attack2,
        Chest_Default,
        Chest_Active,
        Checkpoint_Default,
        Checkpoint_Active,
    }
}